name: "interop-be-domains-analytics-writer"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-domains-analytics-writer-dev"

service:
  create: false

configmap:

deployment:
  flywayInitContainer:
    create: true
    migrationsConfigmap: "common-flyway-domains-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "dev"
      FLYWAY_URL: $(REDSHIFT_JDBC_URL)
      FLYWAY_SCHEMAS: "domains"
    envFromConfigmaps:
      REDSHIFT_JDBC_URL: "common-redshift.REDSHIFT_JDBC_URL"
    envFromSecrets:
      FLYWAY_USER: "redshift-domains-analytics-writer-user.username"
      FLYWAY_PASSWORD: "redshift-domains-analytics-writer-user.password"

  envFromConfigmaps:
    REDSHIFT_JDBC_URL: "common-redshift.REDSHIFT_JDBC_URL"
    REDSHIFT_DB_NAME: "common-redshift.REDSHIFT_DB_NAME"
    REDSHIFT_DB_PORT: "common-redshift.REDSHIFT_DB_PORT"
    REDSHIFT_DB_SCHEMA: "common-redshift.REDSHIFT_DB_DOMAINS_SCHEMA"
  envFromSecrets:
    REDSHIFT_USERNAME: "redshift-domains-analytics-writer-user.username"
    REDSHIFT_PASSWORD: "redshift-domains-analytics-writer-user.password"