# Helm dependencies setup #
-- Add PagoPA eks repos --
-- Update PagoPA eks repo --
NAME                                VERSION         REPOSITORY          
interop-eks-microservice-chart      1.9.2           https://pagopa.github.io/interop-eks-microservice-chart
interop-eks-cronjob-chart           1.5.1           https://pagopa.github.io/interop-eks-cronjob-chart
                                                                        
/Users/lap-mbp16-n01-0319/Desktop/workspace/interop/interop-analytics-deployment/charts
-- Helm dependencies setup ended --
---
# Source: interop-eks-microservice-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: interop-be-jwt-audit-analytics-writer
  namespace: dev-analytics
  labels:
    app.kubernetes.io/name: interop-be-jwt-audit-analytics-writer
    helm.sh/chart: interop-eks-microservice-chart-1.9.2
    app: interop-be-jwt-audit-analytics-writer
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::505630707203:role/interop-be-jwt-audit-analytics-writer-dev"
---
# Source: interop-eks-microservice-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: interop-be-jwt-audit-analytics-writer
  namespace: dev-analytics
data:
  BATCH_SIZE: "500"
  S3_BUCKET: "interop-jwt-audit-analytics-bucket"
  SERVICE_NAME: "pagopa-interop-jwt-audit-analytics-writer"
  SQS_NOTIFICATION_ENDPOINT: "https://sqs.eu-south-1.amazonaws.com/505630707203/interop-analytics-jwt-audit-dev"
---
# Source: interop-eks-microservice-chart/templates/deployment.nodejs.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interop-be-jwt-audit-analytics-writer
  namespace: dev-analytics
  labels:
    app.kubernetes.io/name: interop-be-jwt-audit-analytics-writer
    helm.sh/chart: interop-eks-microservice-chart-1.9.2
    app: interop-be-jwt-audit-analytics-writer
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-jwt-audit-analytics-writer
  template:
    metadata:
      labels:
        actorSystemName: "interop-be-jwt-audit-analytics-writer"
        app.kubernetes.io/name: interop-be-jwt-audit-analytics-writer
        helm.sh/chart: interop-eks-microservice-chart-1.9.2
        app: interop-be-jwt-audit-analytics-writer
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
      annotations:
        digest:  # Used to force deployment on same image version but different content
    spec:
      serviceAccountName: "interop-be-jwt-audit-analytics-writer"
      initContainers:
        - name: migrate-db
          image: flyway/flyway:8.2.3
          args:
            - migrate
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-redshift
                  key: JDBC_URL
            - name: "FLYWAY_CREATE_SCHEMAS"
              value: "true"
            - name: "FLYWAY_PLACEHOLDERS_NAMESPACE"
              value: "dev"
            - name: "FLYWAY_PLACEHOLDER_REPLACEMENT"
              value: "true"
            - name: "FLYWAY_SCHEMAS"
              value: "jwt"
            - name: "FLYWAY_URL"
              value: "$(JDBC_URL)"
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redshift-flyway-user
                  key: password
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: redshift-flyway-user
                  key: username
          volumeMounts:
            - name: migrations-files
              mountPath: "/flyway/sql"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      containers:
        - name: interop-be-jwt-audit-analytics-writer
          image: "505630707203.dkr.ecr.eu-south-1.amazonaws.com/interop-be-jwt-audit-analytics-writer:develop"
          imagePullPolicy: Always # End livenessProbe # End readinessProbe
          ports:
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1001
          env:
            - name: BATCH_SIZE
              valueFrom:
                configMapKeyRef:
                  name: "interop-be-jwt-audit-analytics-writer"
                  key: BATCH_SIZE
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: "interop-be-jwt-audit-analytics-writer"
                  key: S3_BUCKET
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: "interop-be-jwt-audit-analytics-writer"
                  key: SERVICE_NAME
            - name: SQS_NOTIFICATION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "interop-be-jwt-audit-analytics-writer"
                  key: SQS_NOTIFICATION_ENDPOINT
            - name: MERGE_TABLE_SUFFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: "LOG_LEVEL"
              value: "info"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-redshift
                  key: JDBC_URL
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: common-redshift
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: common-redshift
                  key: DB_PORT
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: common-redshift
                  key: DB_JWT_SCHEMA
            - name: REDSHIFT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redshift-jwt-audit-analytics-writer-user
                  key: password
            - name: REDSHIFT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: redshift-jwt-audit-analytics-writer-user
                  key: username
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
      volumes:
        - name: migrations-files
          projected:
            sources:
              - configMap:
                  name: common-flyway-jwt-schema
