apiVersion: v1
kind: ConfigMap
metadata:
  name: common-flyway-jwt-schema
  namespace: qa-analytics
data:
  V1__jwt_Schema.sql: |-
    CREATE SCHEMA IF NOT EXISTS jwt;

    GRANT USAGE ON SCHEMA jwt TO
      ${NAMESPACE}_jwt_audit_analytics_writer_user;

    GRANT USAGE ON SCHEMA jwt TO GROUP
      readonly_group;

    GRANT CREATE, ALTER, DROP ON SCHEMA jwt TO 
      ${NAMESPACE}_jwt_audit_analytics_writer_user;

    CREATE TABLE IF NOT EXISTS jwt.generated_token_audit (
      jwt_id VARCHAR(36) PRIMARY KEY,
      correlation_id VARCHAR(36),
      issued_at BIGINT NOT NULL,
      issued_at_tz TIMESTAMPTZ NOT NULL,
      client_id VARCHAR(36) NOT NULL,
      organization_id VARCHAR(36) NOT NULL,
      agreement_id VARCHAR(36) NOT NULL,
      eservice_id VARCHAR(36) NOT NULL,
      descriptor_id VARCHAR(36) NOT NULL,
      purpose_id VARCHAR(36) NOT NULL,
      purpose_version_id VARCHAR(36) NOT NULL,
      algorithm VARCHAR(50) NOT NULL,
      key_id VARCHAR(255) NOT NULL,
      audience VARCHAR(255) NOT NULL,
      subject VARCHAR(255) NOT NULL,
      not_before BIGINT NOT NULL,
      not_before_tz TIMESTAMPTZ NOT NULL,
      expiration_time BIGINT NOT NULL,
      expiration_time_tz TIMESTAMPTZ NOT NULL,
      issuer VARCHAR(255) NOT NULL,
      client_assertion_jwt_id VARCHAR(36) NOT NULL
    );

    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE jwt.generated_token_audit TO
      ${NAMESPACE}_jwt_audit_analytics_writer_user;

    CREATE TABLE IF NOT EXISTS jwt.client_assertion_audit (
      jwt_id VARCHAR(36),
      issued_at BIGINT NOT NULL,
      issued_at_tz TIMESTAMPTZ NOT NULL,
      algorithm VARCHAR(50) NOT NULL,
      key_id VARCHAR(255) NOT NULL,
      issuer VARCHAR(255) NOT NULL,
      subject VARCHAR(36) NOT NULL,
      audience VARCHAR(255) NOT NULL,
      expiration_time BIGINT NOT NULL,
      expiration_time_tz TIMESTAMPTZ NOT NULL,
      generated_token_jwt_id VARCHAR(36) PRIMARY KEY,
      CONSTRAINT fk_generated_token FOREIGN KEY (generated_token_jwt_id) REFERENCES jwt.generated_token_audit(jwt_id)
    );

    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE jwt.client_assertion_audit TO
      ${NAMESPACE}_jwt_audit_analytics_writer_user;

  V1.0.1__Client_Assertion_Id_resize.sql: |-
    ALTER TABLE jwt.generated_token_audit
      ALTER COLUMN client_assertion_jwt_id TYPE VARCHAR(255);
    ALTER TABLE jwt.client_assertion_audit
      ALTER COLUMN jwt_id TYPE VARCHAR(255);

  V1.0.2__Client_Assertion_Add_raw_timestamps.sql: |-
    ALTER TABLE jwt.client_assertion_audit
      ADD COLUMN issued_at_raw DOUBLE PRECISION NOT NULL,
      ADD COLUMN expiration_time_raw DOUBLE PRECISION NOT NULL;
