apiVersion: v1
kind: ConfigMap
metadata:
  name: common-kafka
  namespace: qa-analytics
data:
  KAFKA_BROKERS: "b-3.interopplatformevents.js15v7.c4.kafka.eu-south-1.amazonaws.com:9098,b-2.interopplatformevents.js15v7.c4.kafka.eu-south-1.amazonaws.com:9098,b-1.interopplatformevents.js15v7.c4.kafka.eu-south-1.amazonaws.com:9098"
  KAFKA_AVERAGE_MESSAGE_SIZE_IN_BYTES: "1000"
  KAFKA_MAX_WAIT_BATCH_MILLIS: "60000"
  KAFKA_MESSAGES_TO_READ_PER_BATCH: "1000"
  KAFKA_TOPIC_STARTING_OFFSET: "earliest"
  APPLICATION_AUDIT_TOPIC: "qa_application.audit"
  CATALOG_TOPIC: "event-store.qa_catalog.events"
  AUTHORIZATION_TOPIC: "event-store.qa_authorization.events"
  AGREEMENT_TOPIC: "event-store.qa_agreement.events"
  ATTRIBUTE_TOPIC: "event-store.qa_attribute_registry.events"
  PURPOSE_TOPIC: "event-store.qa_purpose.events"
  TENANT_TOPIC: "event-store.qa_tenant.events"
  DELEGATION_TOPIC: "event-store.qa_delegation.events"
  ESERVICE_TEMPLATE_TOPIC: "event-store.qa_eservice_template.events"
