name: "interop-be-jwt-audit-analytics-writer"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-jwt-audit-analytics-writer-dev"

service:
  create: false

configmap:
  SERVICE_NAME: pagopa-interop-jwt-audit-analytics-writer
  LOG_LEVEL: info
  SQS_NOTIFICATION_ENDPOINT: https://sqs.eu-south-1.amazonaws.com/505630707203/interop-analytics-jwt-audit-dev
  MERGE_TABLE_SUFFIX: _staging
  S3_BUCKET: interop-jwt-audit-analytics-bucket
  BATCH_SIZE: 500

deployment:
  flywayInitContainer:
    create: true
    migrationsConfigmap: "common-flyway-jwt-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "dev"
      FLYWAY_URL: $(JDBC_URL)
      FLYWAY_SCHEMAS: "jwt_generated"
    envFromConfigmaps:
      DB_HOST: "common-redshift.JDBC_URL"
    envFromSecrets:
      FLYWAY_USER: "redshift-flyway-user.username"
      FLYWAY_PASSWORD: "redshift-flyway-user.password"

  envFromConfigmaps:
    DB_HOST: "common-redshift.JDBC_URL"
    DB_NAME: "common-redshift.DB_NAME"
    DB_PORT: "common-redshift.DB_PORT"
    DB_SCHEMA: "common-redshift.DB_JWT_SCHEMA"
  envFromSecrets:
    REDSHIFT_USERNAME: "redshift-jwt-audit-analytics-writer-user.username"
    REDSHIFT_PASSWORD: "redshift-jwt-audit-analytics-writer-user.password"
  envFromFieldRef:
    MERGE_TABLE_SUFFIX: "metadata.uid"
