name: "interop-be-jwt-audit-analytics-writer"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-jwt-audit-analytics-writer-dev"

service:
  create: false

configmap:

deployment:
  envFromConfigmaps:
    REDSHIFT_JDBC_URL: "common-redshift.REDSHIFT_JDBC_URL"
    REDSHIFT_DB_NAME: "common-redshift.REDSHIFT_DB_NAME"
    REDSHIFT_DB_PORT: "common-redshift.REDSHIFT_DB_PORT"
    REDSHIFT_DB_SCHEMA: "common-redshift.REDSHIFT_DB_JWT_SCHEMA"
  envFromSecrets:
    REDSHIFT_USERNAME: "redshift-jwt-audit-analytics-writer-user.username"
    REDSHIFT_PASSWORD: "redshift-jwt-audit-analytics-writer-user.password"