name: "interop-be-application-audit-analytics-writer"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-application-audit-analytics-writer-dev"

service:
  create: false

configmap:
  SERVICE_NAME: pagopa-interop-application-audit-analytics-writer-dev
  KAFKA_GROUP_ID: "application-audit-analytics-writer-dev"

deployment:
  flywayInitContainer:
    create: true
    version: "11.4.0"
    downloadRedshiftDriver: true
    migrationsConfigmap: "common-flyway-application-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "dev"
      FLYWAY_URL: jdbc:redshift://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
      FLYWAY_SCHEMAS: "application"
    envFromConfigmaps:
      DB_HOST: "common-redshift.DB_HOST"
      DB_PORT: "common-redshift.DB_PORT"
      DB_NAME: "common-redshift.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "redshift-flyway-user.username"
      FLYWAY_PASSWORD: "redshift-flyway-user.password"

  envFromConfigmaps:
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    KAFKA_TOPIC: "common-kafka.APPLICATION_AUDIT_TOPIC"
    DB_HOST: "common-redshift.DB_HOST"
    DB_NAME: "common-redshift.DB_NAME"
    DB_PORT: "common-redshift.DB_PORT"
    DB_USE_SSL: "common-redshift.DB_USE_SSL"
    DB_SCHEMA_NAME: "common-redshift.DB_APPLICATION_SCHEMA"
  envFromSecrets:
    DB_USERNAME: "redshift-application-audit-analytics-writer-user.username"
    DB_PASSWORD: "redshift-application-audit-analytics-writer-user.password"
  envFromFieldRef:
    KAFKA_CLIENT_ID: "metadata.name"
    MERGE_TABLE_SUFFIX: "metadata.uid"
