apiVersion: v1
kind: ConfigMap
metadata:
  name: common-flyway-jwt-generated-schema
  namespace: dev
data:
  V1__Jwt_Generated_Schema.sql: |-
    CREATE SCHEMA IF NOT EXISTS jwt_generated;

    GRANT USAGE ON SCHEMA jwt_generated TO
      interop_be_jwt_audit_analytics_writer_${NAMESPACE},
      interop_analytics_readonly;

    CREATE TABLE IF NOT EXISTS jwt_generated.client_assertion_audit_details (
      jwt_id UUID PRIMARY KEY,
      issued_at TIMESTAMPTZ NOT NULL,
      algorithm VARCHAR(50) NOT NULL,
      key_id VARCHAR(255) NOT NULL,
      issuer VARCHAR(255) NOT NULL,
      subject UUID NOT NULL,
      audience VARCHAR(255) NOT NULL,
      expiration_time TIMESTAMPTZ NOT NULL
    );

    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE jwt_generated.client_assertion_audit_details TO
      interop_be_jwt_audit_analytics_writer_${NAMESPACE};

    GRANT SELECT ON TABLE jwt_generated.client_assertion_audit_details TO
      interop_analytics_readonly;

    CREATE TABLE IF NOT EXISTS jwt_generated.generated_token_audit_details (
      jwt_id UUID PRIMARY KEY,
      correlation_id UUID NOT NULL,
      issued_at TIMESTAMPTZ NOT NULL,
      client_id UUID NOT NULL,
      organization_id UUID NOT NULL,
      agreement_id UUID NOT NULL,
      eservice_id UUID NOT NULL,
      descriptor_id UUID NOT NULL,
      purpose_id UUID NOT NULL,
      purpose_version_id UUID NOT NULL,
      algorithm VARCHAR(50) NOT NULL,
      key_id VARCHAR(255) NOT NULL,
      audience VARCHAR(255) NOT NULL,
      subject VARCHAR(255) NOT NULL,
      not_before TIMESTAMPTZ NOT NULL,
      expiration_time TIMESTAMPTZ NOT NULL,
      issuer VARCHAR(255) NOT NULL,
      client_assertion_jwt_id UUID NOT NULL,
      CONSTRAINT fk_client_assertion FOREIGN KEY (client_assertion_jwt_id) REFERENCES jwt_generated.client_assertion_audit_details(jwt_id) ON DELETE CASCADE
    );

    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE jwt_generated.generated_token_audit_details TO
      interop_be_jwt_audit_analytics_writer_${NAMESPACE};

    GRANT SELECT ON TABLE jwt_generated.generated_token_audit_details TO
      interop_analytics_readonly;
