name: "interop-be-jwt-audit-analytics-writer"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-jwt-audit-analytics-writer-dev"

service:
  create: false

configmap:
  SERVICE_NAME: pagopa-interop-jwt-audit-analytics-writer
  SQS_NOTIFICATION_ENDPOINT: https://sqs.eu-south-1.amazonaws.com/505630707203/interop-analytics-jwt-audit-dev
  S3_BUCKET: interop-generated-jwt-details-dev-es1
  BATCH_SIZE: 500
  TEST_ANNOTATIONS_1: "foo"
  TEST_ANNOTATIONS_2: {{.Values.deployment.env.TEST_ANNOTATIONS_0}} 
  TEST_ANNOTATIONS_3: {{.Values.deployment.env.TEST_ANNOTATIONS_1}} 

deployment:
  enableRolloutAnnotations: true
  flywayInitContainer:
    create: true
    version: "11.4.0"
    downloadRedshiftDriver: true
    migrationsConfigmap: "common-flyway-jwt-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "dev"
      FLYWAY_URL: jdbc:redshift://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
      FLYWAY_SCHEMAS: "jwt"
    envFromConfigmaps:
      DB_HOST: "common-redshift.DB_HOST"
      DB_PORT: "common-redshift.DB_PORT"
      DB_NAME: "common-redshift.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "redshift-flyway-user.username"
      FLYWAY_PASSWORD: "redshift-flyway-user.password"
  env:
    LOG_LEVEL: "debug"
    TEST_ANNOTATIONS_0: "test"
    
  envFromConfigmaps:
    DB_HOST: "common-redshift.DB_HOST"
    DB_NAME: "common-redshift.DB_NAME"
    DB_PORT: "common-redshift.DB_PORT"
    DB_USE_SSL: "common-redshift.DB_USE_SSL"
    DB_SCHEMA_NAME: "common-redshift.DB_JWT_SCHEMA"
  envFromSecrets:
    DB_USERNAME: "redshift-jwt-audit-analytics-writer-user.username"
    DB_PASSWORD: "redshift-jwt-audit-analytics-writer-user.password"
  envFromFieldRef:
    MERGE_TABLE_SUFFIX: "metadata.uid"
