name: "interop-be-alb-logs-analytics-writer"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-alb-logs-analytics-writer-dev"

service:
  create: false

configmap:
  SQS_NOTIFICATION_ENDPOINT: "interop-analytics-alb-logs-dev"
  S3_BUCKET: "interop-alb-logs-dev-es1"

deployment:
  flywayInitContainer:
    create: true
    migrationsConfigmap: "common-flyway-jwt-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "dev"
      FLYWAY_URL: $(JDBC_URL)
      FLYWAY_SCHEMAS: "alb_logs"
    envFromConfigmaps:
      DB_HOST: "common-redshift.JDBC_URL"
    envFromSecrets:
      FLYWAY_USER: "redshift-flyway-user.username"
      FLYWAY_PASSWORD: "redshift-flyway-user.password"

  envFromConfigmaps:
    DB_HOST: "common-redshift.JDBC_URL"
    DB_NAME: "common-redshift.DB_NAME"
    DB_PORT: "common-redshift.DB_PORT"
    DB_SCHEMA: "common-redshift.DB_ALB_LOGS_SCHEMA"
  envFromSecrets:
    REDSHIFT_USERNAME: "redshift-alb-logs-analytics-writer-user.username"
    REDSHIFT_PASSWORD: "redshift-alb-logs-analytics-writer-user.password"
  envFromFieldRef:
    MERGE_TABLE_SUFFIX: "metadata.uid"