name: "interop-be-domains-analytics-writer"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-domains-analytics-writer-dev"

service:
  create: false

configmap:

deployment:
  flywayInitContainer:
    create: true
    version: "11.4.0"
    downloadRedshiftDriver: true
    migrationsConfigmap: "common-flyway-domains-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "dev"
      FLYWAY_URL: jdbc:redshift://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
      FLYWAY_SCHEMAS: "domains"
    envFromConfigmaps:
      DB_HOST: "common-redshift.DB_HOST"
      DB_PORT: "common-redshift.DB_PORT"
      DB_NAME: "common-redshift.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "redshift-flyway-user.username"
      FLYWAY_PASSWORD: "redshift-flyway-user.password"
      
  envFromConfigmaps:
    DB_HOST: "common-redshift.DB_HOST"
    DB_NAME: "common-redshift.DB_NAME"
    DB_PORT: "common-redshift.DB_PORT"
    DB_USE_SSL: "common-redshift.DB_USE_SSL"
    DB_SCHEMA_NAME: "common-redshift.DB_DOMAINS_SCHEMA"
  envFromSecrets:
    DB_USERNAME: "redshift-domains-analytics-writer-user.username"
    DB_PASSWORD: "redshift-domains-analytics-writer-user.password"
  envFromFieldRef:
    MERGE_TABLE_SUFFIX: "metadata.uid"
