name: "interop-be-domains-analytics-writer"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-domains-analytics-writer-dev"

service:
  create: false

configmap:
  SERVICE_NAME: pagopa-interop-domains-analytics-writer-dev
  KAFKA_GROUP_ID: "{{.Values.namespace}}-domains-analytics-writer"

deployment:
  flywayInitContainer:
    create: true
    version: "11.4.0"
    downloadRedshiftDriver: true
    migrationsConfigmap: "common-flyway-domains-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "dev"
      FLYWAY_URL: jdbc:redshift://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
      FLYWAY_SCHEMAS: "domains"
    envFromConfigmaps:
      DB_HOST: "common-redshift.DB_HOST"
      DB_PORT: "common-redshift.DB_PORT"
      DB_NAME: "common-redshift.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "redshift-flyway-user.username"
      FLYWAY_PASSWORD: "redshift-flyway-user.password"

  envFromConfigmaps:
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    AVERAGE_KAFKA_MESSAGE_SIZE_IN_BYTES: "common-kafka.KAFKA_AVERAGE_MESSAGE_SIZE_IN_BYTES"
    MAX_WAIT_KAFKA_BATCH_MILLIS: "common-kafka.KAFKA_MAX_WAIT_BATCH_MILLIS"
    MESSAGES_TO_READ_PER_BATCH: "common-kafka.KAFKA_MESSAGES_TO_READ_PER_BATCH"
    CATALOG_TOPIC: "common-kafka.CATALOG_TOPIC"
    AUTHORIZATION_TOPIC: "common-kafka.AUTHORIZATION_TOPIC"
    AGREEMENT_TOPIC: "common-kafka.AGREEMENT_TOPIC"
    ATTRIBUTE_TOPIC: "common-kafka.ATTRIBUTE_TOPIC"
    PURPOSE_TOPIC: "common-kafka.PURPOSE_TOPIC"
    TENANT_TOPIC: "common-kafka.TENANT_TOPIC"
    DELEGATION_TOPIC: "common-kafka.DELEGATION_TOPIC"
    ESERVICE_TEMPLATE_TOPIC: "common-kafka.ESERVICE_TEMPLATE_TOPIC"
    ANALYTICS_SQL_DB_HOST: "common-redshift.DB_HOST"
    ANALYTICS_SQL_DB_NAME: "common-redshift.DB_NAME"
    ANALYTICS_SQL_DB_PORT: "common-redshift.DB_PORT"
    ANALYTICS_SQL_DB_SCHEMA_NAME: "common-redshift.DB_DOMAINS_SCHEMA"
    ANALYTICS_SQL_DB_USE_SSL: "common-redshift.DB_USE_SSL"
  envFromSecrets:
    ANALYTICS_SQL_DB_USERNAME: "redshift-domains-analytics-writer-user.username"
    ANALYTICS_SQL_DB_PASSWORD: "redshift-domains-analytics-writer-user.password"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
    KAFKA_CLIENT_ID: "metadata.name"
    MERGE_TABLE_SUFFIX: "metadata.uid"
