name: "interop-be-alb-logs-analytics-writer"

serviceAccount:
  roleArn: "arn:aws:iam::755649575658:role/interop-be-alb-logs-analytics-writer-qa"

service:
  create: false

configmap:
  SERVICE_NAME: pagopa-interop-alb-logs-analytics-writer
  SQS_NOTIFICATION_ENDPOINT: https://sqs.eu-south-1.amazonaws.com/755649575658/interop-analytics-alb-logs-qa
  S3_BUCKET: interop-alb-logs-qa-es1

deployment:
  flywayInitContainer:
    create: true
    version: "11.4.0"
    downloadRedshiftDriver: true
    migrationsConfigmap: "common-flyway-infra-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "qa"
      FLYWAY_URL: jdbc:redshift://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
      FLYWAY_SCHEMAS: "infra"
    envFromConfigmaps:
      DB_HOST: "common-redshift.DB_HOST"
      DB_PORT: "common-redshift.DB_PORT"
      DB_NAME: "common-redshift.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "redshift-flyway-user.username"
      FLYWAY_PASSWORD: "redshift-flyway-user.password"

  envFromConfigmaps:
    DB_HOST: "common-redshift.DB_HOST"
    DB_NAME: "common-redshift.DB_NAME"
    DB_PORT: "common-redshift.DB_PORT"
    DB_USE_SSL: "common-redshift.DB_USE_SSL"
    DB_SCHEMA_NAME: "common-redshift.DB_ALB_LOGS_SCHEMA"
  envFromSecrets:
    DB_USERNAME: "redshift-alb-logs-analytics-writer-user.username"
    DB_PASSWORD: "redshift-alb-logs-analytics-writer-user.password"
  envFromFieldRef:
    MERGE_TABLE_SUFFIX: "metadata.uid"